/*
 * FILE : O:\src\pywin32\com\win32comext\mapi\src\PyIMAPIProp.cpp
 * 
 * This file was automatically generated by :
 * Simplified Wrapper and Interface Generator (SWIG)
 * Version 1.1 (Patch 5)
 * 
 * Portions Copyright (c) 1995-1998
 * The University of Utah and The Regents of the University of California.
 * Permission is granted to distribute this file in any manner provided
 * this notice remains intact.
 * 
 * Do not make changes to this file--changes will be lost!
 *
 */


#define SWIGCODE
/* Implementation : PYTHON */

#define SWIGPYTHON
#include <string.h>
#include <stdlib.h>
/***********************************************************************
 * $Header$
 * swig_lib/python/python.cfg
 *
 * This file contains coded needed to add variable linking to the
 * Python interpreter.   C variables are added as a new kind of Python
 * datatype.
 *
 * Also contains supporting code for building python under Windows
 * and things like that.
 *
 * $Log$
 * Revision 1.1  2000/03/14 23:34:06  mhammond
 * Needed to modify a standard Swig file to avoid the 'extern "C"' around Python.h (which gets upset when it tries to include whcar.h as part of the new Unicode patches)
 *
 ************************************************************************/

#include "Python.h"

/* Definitions for Windows/Unix exporting */
#if defined(__WIN32__)
#   if defined(_MSC_VER)
#	define SWIGEXPORT(a,b) __declspec(dllexport) a b
#   else
#	if defined(__BORLANDC__)
#	    define SWIGEXPORT(a,b) a _export b
#	else
#	    define SWIGEXPORT(a,b) a b
#	endif
#   endif
#else
#   define SWIGEXPORT(a,b) a b
#endif

#ifdef SWIG_GLOBAL
#ifdef __cplusplus
#define SWIGSTATIC extern "C"
#else
#define SWIGSTATIC
#endif
#endif

#ifndef SWIGSTATIC
#define SWIGSTATIC static
#endif

#ifdef NEED_SWIG_VARLINK

typedef struct {
  char  *name;
  PyObject *(*get_attr)(void);
  int (*set_attr)(PyObject *);
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar **vars;
  int      nvars;
  int      maxvars;
} swig_varlinkobject;

/* ----------------------------------------------------------------------
   swig_varlink_repr()

   Function for python repr method
   ---------------------------------------------------------------------- */

static PyObject *
swig_varlink_repr(swig_varlinkobject *v)
{
  v = v;
  return PyString_FromString("<Global variables>");
}

/* ---------------------------------------------------------------------
   swig_varlink_print()

   Print out all of the global variable names
   --------------------------------------------------------------------- */

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags)
{

  int i = 0;
  flags = flags;
  fprintf(fp,"Global variables { ");
  while (v->vars[i]) {
    fprintf(fp,"%s", v->vars[i]->name);
    i++;
    if (v->vars[i]) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

/* --------------------------------------------------------------------
   swig_varlink_getattr
 
   This function gets the value of a variable and returns it as a
   PyObject.   In our case, we'll be looking at the datatype and
   converting into a number or string
   -------------------------------------------------------------------- */

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n)
{
  int i = 0;
  char temp[128];

  while (v->vars[i]) {
    if (strcmp(v->vars[i]->name,n) == 0) {
      return (*v->vars[i]->get_attr)();
    }
    i++;
  }
  sprintf(temp,"C global variable %s not found.", n);
  PyErr_SetString(PyExc_NameError,temp);
  return NULL;
}

/* -------------------------------------------------------------------
   swig_varlink_setattr()

   This function sets the value of a variable.
   ------------------------------------------------------------------- */

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p)
{
  char temp[128];
  int i = 0;
  while (v->vars[i]) {
    if (strcmp(v->vars[i]->name,n) == 0) {
      return (*v->vars[i]->set_attr)(p);
    }
    i++;
  }
  sprintf(temp,"C global variable %s not found.", n);
  PyErr_SetString(PyExc_NameError,temp);
  return 1;
}

statichere PyTypeObject varlinktype = {
/*  PyObject_HEAD_INIT(&PyType_Type)  Note : This doesn't work on some machines */
  PyObject_HEAD_INIT(0)              
  0,
  "varlink",                          /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */

SWIGSTATIC PyObject *
SWIG_newvarlink(void)
{
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  /*  _Py_NewReference(result);  Does not seem to be necessary */
  result->nvars = 0;
  result->maxvars = 64;
  result->vars = (swig_globalvar **) malloc(64*sizeof(swig_globalvar *));
  result->vars[0] = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGSTATIC void
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p))
{
  swig_varlinkobject *v;
  v= (swig_varlinkobject *) p;
	
  if (v->nvars >= v->maxvars -1) {
    v->maxvars = 2*v->maxvars;
    v->vars = (swig_globalvar **) realloc(v->vars,v->maxvars*sizeof(swig_globalvar *));
    if (v->vars == NULL) {
      fprintf(stderr,"SWIG : Fatal error in initializing Python module.\n");
      exit(1);
    }
  }
  v->vars[v->nvars] = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  v->vars[v->nvars]->name = (char *) malloc(strlen(name)+1);
  strcpy(v->vars[v->nvars]->name,name);
  v->vars[v->nvars]->get_attr = get_attr;
  v->vars[v->nvars]->set_attr = set_attr;
  v->nvars++;
  v->vars[v->nvars] = 0;
}

#else
#define SWIG_newvarlink() Py_None
#endif /* SWIG_NEED_VARLINK */
#ifdef NEED_SWIG_PTR
/*****************************************************************************
 * $Header$
 *
 * swigptr.swg
 *
 * This file contains supporting code for the SWIG run-time type checking
 * mechanism.  The following functions are available :
 *
 * SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *));
 *
 *      Registers a new type-mapping with the type-checker.  origtype is the
 *      original datatype and newtype is an equivalent type.  cast is optional
 *      pointer to a function to cast pointer values between types (this
 *      is typically used to cast pointers from derived classes to base classes in C++)
 *      
 * SWIG_MakePtr(char *buffer, void *ptr, char *typestring);
 *     
 *      Makes a pointer string from a pointer and typestring.  The result is returned
 *      in buffer which is assumed to hold enough space for the result.
 *
 * char * SWIG_GetPtr(char *buffer, void **ptr, char *type)
 *
 *      Gets a pointer value from a string.  If there is a type-mismatch, returns
 *      a character string to the received type.  On success, returns NULL.
 *
 *
 * You can remap these functions by making a file called "swigptr.swg" in
 * your the same directory as the interface file you are wrapping.
 *
 * These functions are normally declared static, but this file can be
 * can be used in a multi-module environment by redefining the symbol
 * SWIGSTATIC.
 *****************************************************************************/

#include <stdlib.h>

#ifdef SWIG_GLOBAL
#ifdef __cplusplus
#define SWIGSTATIC extern "C"
#else
#define SWIGSTATIC
#endif
#endif

#ifndef SWIGSTATIC
#define SWIGSTATIC static
#endif


/* SWIG pointer structure */

typedef struct SwigPtrType {
  char               *name;               /* Datatype name                  */
  int                 len;                /* Length (used for optimization) */
  void               *(*cast)(void *);    /* Pointer casting function       */
  struct SwigPtrType *next;               /* Linked list pointer            */
} SwigPtrType;

/* Pointer cache structure */

typedef struct {
  int                 stat;               /* Status (valid) bit             */
  SwigPtrType        *tp;                 /* Pointer to type structure      */
  char                name[256];          /* Given datatype name            */
  char                mapped[256];        /* Equivalent name                */
} SwigCacheType;

/* Some variables  */

static int SwigPtrMax  = 64;           /* Max entries that can be currently held */
                                       /* This value may be adjusted dynamically */
static int SwigPtrN    = 0;            /* Current number of entries              */
static int SwigPtrSort = 0;            /* Status flag indicating sort            */
static int SwigStart[256];             /* Starting positions of types            */

/* Pointer table */
static SwigPtrType *SwigPtrTable = 0;  /* Table containing pointer equivalences  */

/* Cached values */

#define SWIG_CACHESIZE  8
#define SWIG_CACHEMASK  0x7
static SwigCacheType SwigCache[SWIG_CACHESIZE];  
static int SwigCacheIndex = 0;
static int SwigLastCache = 0;

/* Sort comparison function */
static int swigsort(const void *data1, const void *data2) {
	SwigPtrType *d1 = (SwigPtrType *) data1;
	SwigPtrType *d2 = (SwigPtrType *) data2;
	return strcmp(d1->name,d2->name);
}

/* Binary Search function */
static int swigcmp(const void *key, const void *data) {
  char *k = (char *) key;
  SwigPtrType *d = (SwigPtrType *) data;
  return strncmp(k,d->name,d->len);
}

/* Register a new datatype with the type-checker */

SWIGSTATIC 
void SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *)) {

  int i;
  SwigPtrType *t = 0,*t1;

  /* Allocate the pointer table if necessary */

  if (!SwigPtrTable) {     
    SwigPtrTable = (SwigPtrType *) malloc(SwigPtrMax*sizeof(SwigPtrType));
    SwigPtrN = 0;
  }
  /* Grow the table */
  if (SwigPtrN >= SwigPtrMax) {
    SwigPtrMax = 2*SwigPtrMax;
    SwigPtrTable = (SwigPtrType *) realloc((char *) SwigPtrTable,SwigPtrMax*sizeof(SwigPtrType));
  }
  for (i = 0; i < SwigPtrN; i++)
    if (strcmp(SwigPtrTable[i].name,origtype) == 0) {
      t = &SwigPtrTable[i];
      break;
    }
  if (!t) {
    t = &SwigPtrTable[SwigPtrN];
    t->name = origtype;
    t->len = strlen(t->name);
    t->cast = 0;
    t->next = 0;
    SwigPtrN++;
  }

  /* Check for existing entry */

  while (t->next) {
    if ((strcmp(t->name,newtype) == 0)) {
      if (cast) t->cast = cast;
      return;
    }
    t = t->next;
  }
  
  /* Now place entry (in sorted order) */

  t1 = (SwigPtrType *) malloc(sizeof(SwigPtrType));
  t1->name = newtype;
  t1->len = strlen(t1->name);
  t1->cast = cast;
  t1->next = 0;            
  t->next = t1;           
  SwigPtrSort = 0;
}

/* Make a pointer value string */

SWIGSTATIC 
void SWIG_MakePtr(char *_c, const void *_ptr, char *type) {
  static char _hex[16] =
  {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
   'a', 'b', 'c', 'd', 'e', 'f'};
  unsigned long _p, _s;
  char _result[20], *_r;    /* Note : a 64-bit hex number = 16 digits */
  _r = _result;
  _p = (unsigned long) _ptr;
  if (_p > 0) {
    while (_p > 0) {
      _s = _p & 0xf;
      *(_r++) = _hex[_s];
      _p = _p >> 4;
    }
    *_r = '_';
    while (_r >= _result)
      *(_c++) = *(_r--);
  } else {
    strcpy (_c, "NULL");
  }
  if (_ptr)
    strcpy (_c, type);
}

/* Define for backwards compatibility */

#define _swig_make_hex   SWIG_MakePtr 

/* Function for getting a pointer value */

SWIGSTATIC 
char *SWIG_GetPtr(char *_c, void **ptr, char *_t)
{
  unsigned long _p;
  char temp_type[256];
  char *name;
  int  i, len;
  SwigPtrType *sp,*tp;
  SwigCacheType *cache;
  int  start, end;
  _p = 0;

  /* Pointer values must start with leading underscore */
  if (*_c == '_') {
      _c++;
      /* Extract hex value from pointer */
      while (*_c) {
	  if ((*_c >= '0') && (*_c <= '9'))
	    _p = (_p << 4) + (*_c - '0');
	  else if ((*_c >= 'a') && (*_c <= 'f'))
	    _p = (_p << 4) + ((*_c - 'a') + 10);
	  else
	    break;
	  _c++;
      }

      if (_t) {
	if (strcmp(_t,_c)) { 
	  if (!SwigPtrSort) {
	    qsort((void *) SwigPtrTable, SwigPtrN, sizeof(SwigPtrType), swigsort); 
	    for (i = 0; i < 256; i++) {
	      SwigStart[i] = SwigPtrN;
	    }
	    for (i = SwigPtrN-1; i >= 0; i--) {
	      SwigStart[(int) (SwigPtrTable[i].name[1])] = i;
	    }
	    for (i = 255; i >= 1; i--) {
	      if (SwigStart[i-1] > SwigStart[i])
		SwigStart[i-1] = SwigStart[i];
	    }
	    SwigPtrSort = 1;
	    for (i = 0; i < SWIG_CACHESIZE; i++)  
	      SwigCache[i].stat = 0;
	  }
	  
	  /* First check cache for matches.  Uses last cache value as starting point */
	  cache = &SwigCache[SwigLastCache];
	  for (i = 0; i < SWIG_CACHESIZE; i++) {
	    if (cache->stat) {
	      if (strcmp(_t,cache->name) == 0) {
		if (strcmp(_c,cache->mapped) == 0) {
		  cache->stat++;
		  *ptr = (void *) _p;
		  if (cache->tp->cast) *ptr = (*(cache->tp->cast))(*ptr);
		  return (char *) 0;
		}
	      }
	    }
	    SwigLastCache = (SwigLastCache+1) & SWIG_CACHEMASK;
	    if (!SwigLastCache) cache = SwigCache;
	    else cache++;
	  }
	  /* We have a type mismatch.  Will have to look through our type
	     mapping table to figure out whether or not we can accept this datatype */

	  start = SwigStart[(int) _t[1]];
	  end = SwigStart[(int) _t[1]+1];
	  sp = &SwigPtrTable[start];
	  while (start < end) {
	    if (swigcmp(_t,sp) == 0) break;
	    sp++;
	    start++;
	  }
	  if (start >= end) sp = 0;
	  /* Try to find a match for this */
	  if (sp) {
	    while (swigcmp(_t,sp) == 0) {
	      name = sp->name;
	      len = sp->len;
	      tp = sp->next;
	      /* Try to find entry for our given datatype */
	      while(tp) {
		if (tp->len >= 255) {
		  return _c;
		}
		strncpy(temp_type,tp->name,255);
		strncat(temp_type,_t+len,255-tp->len);
		if (strcmp(_c,temp_type) == 0) {
		  
		  strcpy(SwigCache[SwigCacheIndex].mapped,_c);
		  strcpy(SwigCache[SwigCacheIndex].name,_t);
		  SwigCache[SwigCacheIndex].stat = 1;
		  SwigCache[SwigCacheIndex].tp = tp;
		  SwigCacheIndex = SwigCacheIndex & SWIG_CACHEMASK;
		  
		  /* Get pointer value */
		  *ptr = (void *) _p;
		  if (tp->cast) *ptr = (*(tp->cast))(*ptr);
		  return (char *) 0;
		}
		tp = tp->next;
	      }
	      sp++;
	      /* Hmmm. Didn't find it this time */
	    }
	  }
	  /* Didn't find any sort of match for this data.  
	     Get the pointer value and return the received type */
	  *ptr = (void *) _p;
	  return _c;
	} else {
	  /* Found a match on the first try.  Return pointer value */
	  *ptr = (void *) _p;
	  return (char *) 0;
	}
      } else {
	/* No type specified.  Good luck */
	*ptr = (void *) _p;
	return (char *) 0;
      }
  } else {
    if (strcmp (_c, "NULL") == 0) {
	*ptr = (void *) 0;
	return (char *) 0;
    }
    *ptr = (void *) 0;	
    return _c;
  }
}

/* Compatibility mode */

#define _swig_get_hex  SWIG_GetPtr

#else
#define SWIG_RegisterMapping(a,b,c)
#endif // NEED_SWIG_PTR

static PyObject* t_output_helper(PyObject* target, PyObject* o) {
    PyObject*   o2;
    PyObject*   o3;

    if (!target) {                   
        target = o;
    } else if (target == Py_None) {  
        Py_DECREF(Py_None);
        target = o;
    } else {                            
        if (!PyTuple_Check(target)) {   
            o2 = target;
            target = PyTuple_New(1);
            PyTuple_SetItem(target, 0, o2);
        }
        o3 = PyTuple_New(1);            
        PyTuple_SetItem(o3, 0, o);      

        o2 = target;
        target = PySequence_Concat(o2, o3); 
        Py_DECREF(o2);                      
        Py_DECREF(o3);
    }
    return target;
}

#include "PyWinTypes.h"
#ifdef NEED_PYWINOBJECTS_H
#include "PyWinObjects.h"
#endif
#include "tchar.h"
typedef BOOL  BOOLAPI;
typedef DWORD  DWORDAPI;

#define PyHANDLE HANDLE // Use a #define so we can undef it later if we need the true defn.
//typedef HANDLE PyHKEY;

#include "PythonCOM.h"

#define SWIG_PYTHONCOM
typedef long  HRESULT_KEEP;
typedef long  HRESULT_KEEP_INFO;

#define MAKE_OUTPUT_INTERFACE(source, target, iid) \
{ \
    PyObject *o; \
    o = PyCom_PyObjectFromIUnknown(*source, iid, FALSE /* bAddRef */); \
    if (target==NULL) \
      target = o; \
	else if (target == Py_None) { /* has been incref'd already!*/ \
		Py_DECREF(Py_None); \
		target = o; \
    } else { \
      if (!PyList_Check(target)) { \
        PyObject *o2 = target; \
        target = PyList_New(0); \
        PyList_Append(target,o2); \
        Py_XDECREF(o2); \
      } \
      PyList_Append(target,o); \
      Py_XDECREF(o); \
    } \
}

#include "pymapiutil.h"


#include "PyIMAPIProp.h"

// A little helper just for this file
static PyObject* OleSetTypeError(char *msg)
{
	PyErr_SetString(PyExc_TypeError, msg);
	return NULL;
}


PyIMAPIProp::PyIMAPIProp(IUnknown *pDisp) :
	PyIUnknown(pDisp)
{
	ob_type = &type;
}

PyIMAPIProp::~PyIMAPIProp()
{
}

/*static*/ IMAPIProp *PyIMAPIProp::GetI(PyObject *self)
{
	return (IMAPIProp *)PyIUnknown::GetI(self);
}

// @pyswig int, [items, ]|GetProps|Returns a list of property values.
PyObject *PyIMAPIProp::GetProps(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    HRESULT  _result;
    SPropTagArray * _arg0 = NULL;
    unsigned long  _arg1=0;
    PyObject * _obj0 = 0;

	IMAPIProp *_swig_self;
	if ((_swig_self=GetI(self))==NULL) return NULL;
	// @pyparm <o PySPropTagArray>|propList||The list of properties
	// @pyparm int|flags|0|
    if(!PyArg_ParseTuple(args,"O|l:GetProps",&_obj0,&_arg1)) 
        return NULL;
	if (!PyMAPIObject_AsSPropTagArray(_obj0, &_arg0))
		return NULL;
	ULONG numValues;
	SPropValue *pv;
	Py_BEGIN_ALLOW_THREADS
    _result = (HRESULT )_swig_self->GetProps(_arg0,_arg1, &numValues, &pv);
	Py_END_ALLOW_THREADS
	PyMAPIObject_FreeSPropTagArray(_arg0);
    if (FAILED(_result))  {
       return OleSetOleError(_result);
    }

	_resultobj = PyTuple_New(numValues);
	if (_resultobj==NULL) {
		MAPIFreeBuffer(pv);
		PyErr_SetString(PyExc_MemoryError, "Allocating SRowSet result");
		return NULL;
	}
	for (ULONG i=0;i<numValues;i++) {
		PyObject *newOb = PyMAPIObject_FromSPropValue(pv+i);
		if (newOb==NULL) {
			MAPIFreeBuffer(pv);
			Py_DECREF(_resultobj);
			return NULL;
		}
		PyTuple_SetItem(_resultobj, i, newOb);
		// SetItem() keeps our reference to newOb
	}
	MAPIFreeBuffer(pv);	// all done with it now.
	PyObject *realrc = Py_BuildValue("iO", _result, _resultobj);
	Py_DECREF(_resultobj);
	return realrc;
}

// @pyswig int, [problems, ]|DeleteProps|Deletes a set of properties.
PyObject *PyIMAPIProp::DeleteProps(PyObject *self, PyObject *args) 
{
	PyObject *obs;
    SPropTagArray * _arg0;
	HRESULT hr;
	IMAPIProp *pMAPIProp;
	if ((pMAPIProp=GetI(self))==NULL) return NULL;
	PyObject *myob = NULL;
	// @pyparm <o PySPropTagArray>|propList||The list of properties
    if(!PyArg_ParseTuple(args,"O:DeleteProps",&obs))
		return NULL;
	if (!PyMAPIObject_AsSPropTagArray(obs, &_arg0))
		return NULL;
	Py_BEGIN_ALLOW_THREADS
	hr = pMAPIProp->DeleteProps( _arg0, NULL);
	Py_END_ALLOW_THREADS
	PyMAPIObject_FreeSPropTagArray(_arg0);
	if (FAILED(hr))
		return OleSetOleError(hr);
	return Py_BuildValue("iz", hr, NULL); // None used as place holder for problem array later.
}

// @pyswig int, [problems, ]|SetProps|Sets a set of properties.
PyObject *PyIMAPIProp::SetProps(PyObject *self, PyObject *args) 
{
	PyObject *obs;
	HRESULT hr;
	IMAPIProp *pMAPIProp;
	if ((pMAPIProp=GetI(self))==NULL) return NULL;
	PyObject *myob = NULL;
	// @pyparm [<o PySPropValue>, ]|propList||The list of properties
    if(!PyArg_ParseTuple(args,"O:SetProps",&obs))
		return NULL;
	if (!PySequence_Check(obs)) {
		PyErr_SetString(PyExc_TypeError, "Properties must be a sequence of tuples");
		return NULL;
	}
	SPropValue *pPV;
	ULONG seqLen;
	if (!PyMAPIObject_AsSPropValueArray(obs, &pPV, &seqLen))
		return NULL;
	Py_BEGIN_ALLOW_THREADS
	hr = pMAPIProp->SetProps( seqLen, pPV, NULL);
	Py_END_ALLOW_THREADS
	MAPIFreeBuffer(pPV);
	if (FAILED(hr))
		return OleSetOleError(hr);
	return Py_BuildValue("iz", hr, NULL); // None used as place holder for proplem array later.
}

// @pyswig int, [problems, ]|CopyTo|Copies an object to another
PyObject *PyIMAPIProp::CopyTo(PyObject *self, PyObject *args) 
{
	IID *pExclude = NULL;
	ULONG ciidExclude = 0;
	IID iid;
	IUnknown *pUnk = NULL;
	SPropTagArray *pta = NULL;
	PyObject *result = NULL;
	PyObject *obIIDExclude, *obPropTags, *obDest, *obIID;
	ULONG ulUIParm, flags;
	char *szIgnore;
	HRESULT hr;
	IMAPIProp *pMAPIProp;
	if ((pMAPIProp=GetI(self))==NULL) return NULL;
	// @pyparm [<o PyIID>, ]|IIDExcludeList||A sequence of IIDs to exclude.
	// @pyparm <o PySPropTagArray>|propTags||The property tags to copy
	// @pyparm int|uiFlags||Flags for the progress object
	// @pyparm None|progress||Reserved - must pass None
	// @pyparm <o PyIID>|resultIID||IID of the destination object
	// @pyparm <o PyIMAPIProp>|dest||The destination object
	// @pyparm int|flags||flags
    if(!PyArg_ParseTuple(args,"OOlzOOl:CopyTo",&obIIDExclude, &obPropTags, &ulUIParm, &szIgnore, &obIID, &obDest, &flags))
		return NULL;
	if (obIIDExclude==Py_None)
		pExclude = NULL;
	else {
		if (!PySequence_Check(obIIDExclude)) {
			OleSetTypeError("Argument 1 must be a sequence of IID's, or None");
			goto error;
		}
		ciidExclude = PySequence_Length(obIIDExclude);
		pExclude = new IID[ciidExclude];
		if (pExclude==NULL) {
			PyErr_SetString(PyExc_MemoryError, "Allocating array of IID's");
			goto error;
		}
		for (ULONG i=0;i<ciidExclude;i++) {
			PyObject *ob = PySequence_GetItem(obIIDExclude, (int)i);
			BOOL ok = PyWinObject_AsIID(ob, pExclude+i);
			Py_XDECREF(ob);
			if (!ok) {
				goto error;
			}
		}
	}
	// PropTagArray
	if (!PyMAPIObject_AsSPropTagArray(obPropTags, &pta))
		goto error;
	// IID.
	if (!PyWinObject_AsIID(obIID, &iid))
		goto error;
	// IUnknown.
	if (!PyCom_InterfaceFromPyInstanceOrObject(obDest, IID_IUnknown, (void **)&pUnk, 0))
		goto error;
	// Finally make the call.
	Py_BEGIN_ALLOW_THREADS
	hr = pMAPIProp->CopyTo(ciidExclude, pExclude, pta, ulUIParm, NULL, &iid, (void *)pUnk, flags, NULL );
	Py_END_ALLOW_THREADS
	if (FAILED(hr)) {
		OleSetOleError(hr);
		goto error;
	}
	result = Py_BuildValue("iz", hr, NULL);
error:
	free(pExclude);
	PyMAPIObject_FreeSPropTagArray(pta);
	if (pUnk)
		pUnk->Release();
	return result;
}

// @pyswig int, [problems, ]|CopyProps|Copies a set of properties to another object
PyObject *PyIMAPIProp::CopyProps(PyObject *self, PyObject *args) 
{
	IID iid;
	IUnknown *pUnk = NULL;
	SPropTagArray *pta = NULL;
	PyObject *result = NULL;
	PyObject *obPropTags, *obDest, *obIID;
	ULONG ulUIParm, flags;
	char *szIgnore;
	HRESULT hr;
	IMAPIProp *pMAPIProp;
	if ((pMAPIProp=GetI(self))==NULL) return NULL;
	// @pyparm <o PySPropTagArray>|propTags||The property tags to copy
	// @pyparm int|uiFlags||Flags for the progress object
	// @pyparm None|progress||Reserved - must pass None
	// @pyparm <o PyIID>|resultIID||IID of the destination object
	// @pyparm <o PyIMAPIProp>|dest||The destination object
	// @pyparm int|flags||flags
    if(!PyArg_ParseTuple(args,"OlzOOl:CopyProps",&obPropTags, &ulUIParm, &szIgnore, &obIID, &obDest, &flags))
		return NULL;
	// PropTagArray
	if (!PyMAPIObject_AsSPropTagArray(obPropTags, &pta))
		goto error;
	// IID.
	if (!PyWinObject_AsIID(obIID, &iid))
		goto error;
	// IUnknown.
	if (!PyCom_InterfaceFromPyInstanceOrObject(obDest, IID_IUnknown, (void **)&pUnk, 0))
		goto error;
	// Finally make the call.
	Py_BEGIN_ALLOW_THREADS
	hr = pMAPIProp->CopyProps(pta, ulUIParm, NULL, &iid, (void *)pUnk, flags, NULL );
	Py_END_ALLOW_THREADS
	if (FAILED(hr)) {
		OleSetOleError(hr);
		goto error;
	}
	result = Py_BuildValue("iz", hr, NULL);
error:
	PyMAPIObject_FreeSPropTagArray(pta);
	if (pUnk)
		pUnk->Release();
	return result;
}

// @pyswig <o PyIUnknown>|OpenProperty|Returns an interface object to be used to access a property. 
PyObject *PyIMAPIProp::OpenProperty(PyObject *self, PyObject *args) 
{
	IID iid;
	IUnknown *pUnk = NULL;
	PyObject *obIID;
	ULONG propTag, flags, interfaceOptions;
	HRESULT hr;
	IMAPIProp *pMAPIProp;
	if ((pMAPIProp=GetI(self))==NULL) return NULL;
	// @pyparm int|propTag||The property tag to open
	// @pyparm <o PyIID>|iid||The IID of the resulting interface.
	// @pyparm int|interfaceOptions||Data that relates to the interface identified by the lpiid parameter. 
	// @pyparm int|flags||flags
    if(!PyArg_ParseTuple(args,"lOll:OpenProperty",&propTag, &obIID, &interfaceOptions, &flags))
		return NULL;
	// IID.
	if (!PyWinObject_AsIID(obIID, &iid))
		return NULL;
	// Make the call.
	Py_BEGIN_ALLOW_THREADS
	hr = pMAPIProp->OpenProperty(propTag, &iid, interfaceOptions, flags, &pUnk);
	Py_END_ALLOW_THREADS
	if (FAILED(hr)) {
		return OleSetOleError(hr);
	}
	return PyCom_PyObjectFromIUnknown(pUnk, iid, /*BOOL bAddRef*/ FALSE);
}

// @pyswig <o PySPropTagArray>|GetIDsFromNames|Determines property IDs
PyObject *PyIMAPIProp::GetIDsFromNames(PyObject *self, PyObject *args)
{
	PyObject *obNameIds;
	ULONG flags=0;
	// @pyparm PyMAPINAMEIDArray|nameIds||Sequence of name ids
	// @pyparm int|flags|0|
	if (!PyArg_ParseTuple(args, "O|l:GetIDsFromNames", &obNameIds, &flags))
		return NULL;
	MAPINAMEID **ppIds;
	ULONG numIds = 0;
	IMAPIProp *pMAPIProp;
	if ((pMAPIProp=GetI(self))==NULL) return NULL;
	if (!PyMAPIObject_AsMAPINAMEIDArray(obNameIds, &ppIds, &numIds, TRUE))
		return NULL;
	SPropTagArray *pTagResult;
	HRESULT hr;
	Py_BEGIN_ALLOW_THREADS
	hr = pMAPIProp->GetIDsFromNames(numIds, ppIds, flags, &pTagResult);
	Py_END_ALLOW_THREADS
	PyMAPIObject_FreeMAPINAMEIDArray(ppIds);
	if (FAILED(hr))
		return OleSetOleError(hr);
	PyObject *rc = PyMAPIObject_FromSPropTagArray(pTagResult);
	MAPIFreeBuffer(pTagResult);
	return rc;
}

PyObject *PyIMAPIProp::GetNamesFromIDs(PyObject *self, PyObject *args)
{
	IMAPIProp *pMAPIProp;
	if ((pMAPIProp=GetI(self))==NULL) return NULL;
	PyObject *obTags, *obiid = Py_None;
	ULONG flags=0;
	// @pyparm <o PySPropTagArray>|propTags||Sequence of property tags, or None
	// @pyparm <o PyIID>|propSetGuid|None|a globally unique identifier, identifying a property set, or None
	// @pyparm int|flags|0|
	if (!PyArg_ParseTuple(args, "O|Ol:GetIDsFromNames", &obTags, &obiid, &flags))
		return NULL;
	GUID guid, *pguid = NULL;
	if (obiid != Py_None) {
		pguid = &guid;
		if (!PyWinObject_AsIID(obiid, pguid))
			return NULL;
	}
	SPropTagArray *pta = NULL;
	if (obTags != Py_None)
		if (!PyMAPIObject_AsSPropTagArray(obTags, &pta))
			return NULL;

	ULONG numNames = 0;
	MAPINAMEID **ppNames = NULL;
	HRESULT hr;
	Py_BEGIN_ALLOW_THREADS
	hr = pMAPIProp->GetNamesFromIDs( &pta, pguid, flags, &numNames, &ppNames );
	Py_END_ALLOW_THREADS
	PyObject *result;
	if (SUCCEEDED(hr)) {
		PyObject *obNames = PyMAPIObject_FromMAPINAMEIDArray(ppNames, numNames);
		PyObject *obTags = PyMAPIObject_FromSPropTagArray(pta);
		result = Py_BuildValue("lOO", hr, obTags, obNames);
		Py_XDECREF(obTags);
		Py_XDECREF(obNames);
	} else {
		OleSetOleError(hr);
		result = NULL;
	}
	if (ppNames) MAPIFreeBuffer(ppNames);
	if (pta) PyMAPIObject_FreeSPropTagArray(pta);
	return result;
}
PyObject *PyIMAPIProp::GetLastError(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    HRESULT  _result;
    HRESULT  _arg0;
    unsigned long  _arg1;
    MAPIERROR ** _arg2;
    MAPIERROR * temp;

{
	_arg2 = &temp;
}
	IMAPIProp *_swig_self;
	if ((_swig_self=GetI(self))==NULL) return NULL;
    if(!PyArg_ParseTuple(args,"ll:GetLastError",&_arg0,&_arg1)) 
        return NULL;
{
      Py_BEGIN_ALLOW_THREADS
          _result = (HRESULT )_swig_self->GetLastError(_arg0,_arg1,_arg2);

      Py_END_ALLOW_THREADS
      if (FAILED(_result))  {
           
#ifdef SWIG_THIS_IID
           return PyCom_BuildPyException(_result, _swig_self,  SWIG_THIS_IID);
#else
           return PyCom_BuildPyException(_result);
#endif
      }
}{
	_resultobj = Py_None;
	Py_INCREF(Py_None);
}
{
	PyObject_FromMAPIERROR(*_arg2, TRUE, TRUE);
}
    return _resultobj;
}

PyObject *PyIMAPIProp::SaveChanges(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    HRESULT  _result;
    unsigned long  _arg0;

	IMAPIProp *_swig_self;
	if ((_swig_self=GetI(self))==NULL) return NULL;
    if(!PyArg_ParseTuple(args,"l:SaveChanges",&_arg0)) 
        return NULL;
{
      Py_BEGIN_ALLOW_THREADS
          _result = (HRESULT )_swig_self->SaveChanges(_arg0);

      Py_END_ALLOW_THREADS
      if (FAILED(_result))  {
           
#ifdef SWIG_THIS_IID
           return PyCom_BuildPyException(_result, _swig_self,  SWIG_THIS_IID);
#else
           return PyCom_BuildPyException(_result);
#endif
      }
}{
	_resultobj = Py_None;
	Py_INCREF(Py_None);
}
    return _resultobj;
}

PyObject *PyIMAPIProp::GetPropList(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    HRESULT  _result;
    unsigned long  _arg0;
    SPropTagArray ** _arg1;
    SPropTagArray * temp;

{
	_arg1 = NULL;
}
{
	_arg1 = &temp;
}
	IMAPIProp *_swig_self;
	if ((_swig_self=GetI(self))==NULL) return NULL;
    if(!PyArg_ParseTuple(args,"l:GetPropList",&_arg0)) 
        return NULL;
{
      Py_BEGIN_ALLOW_THREADS
          _result = (HRESULT )_swig_self->GetPropList(_arg0,_arg1);

      Py_END_ALLOW_THREADS
      if (FAILED(_result))  {
           {
	if (*_arg1) MAPIFreeBuffer(*_arg1);
}

#ifdef SWIG_THIS_IID
           return PyCom_BuildPyException(_result, _swig_self,  SWIG_THIS_IID);
#else
           return PyCom_BuildPyException(_result);
#endif
      }
}{
	_resultobj = Py_None;
	Py_INCREF(Py_None);
}
{
	_resultobj = PyMAPIObject_FromSPropTagArray(*_arg1);
	if (_resultobj==NULL) {
		{
	if (*_arg1) MAPIFreeBuffer(*_arg1);
}
;
		return NULL;
	}
}
{
	if (*_arg1) MAPIFreeBuffer(*_arg1);
}
    return _resultobj;
}

static PyMethodDef IMAPIPropMethods[] = {
	 { "GetPropList", PyIMAPIProp::GetPropList, 1 },
	 { "OpenProperty", PyIMAPIProp::OpenProperty, 1 },
	 { "GetIDsFromNames", PyIMAPIProp::GetIDsFromNames, 1 },
	 { "DeleteProps", PyIMAPIProp::DeleteProps, 1 },
	 { "CopyProps", PyIMAPIProp::CopyProps, 1 },
	 { "CopyTo", PyIMAPIProp::CopyTo, 1 },
	 { "SetProps", PyIMAPIProp::SetProps, 1 },
	 { "GetProps", PyIMAPIProp::GetProps, 1 },
	 { "SaveChanges", PyIMAPIProp::SaveChanges, 1 },
	 { "GetLastError", PyIMAPIProp::GetLastError, 1 },
	 { "GetNamesFromIDs", PyIMAPIProp::GetNamesFromIDs, 1 },
	 { NULL, NULL }
};
PyComTypeObject PyIMAPIProp::type("PyIMAPIProp",	&PyIUnknown::type,
	sizeof(PyIMAPIProp),
	IMAPIPropMethods,
	GET_PYCOM_CTOR(PyIMAPIProp));
#ifndef SWIG_PYTHONCOM
/* This code only valid if non COM SWIG builds */
#ifndef PYCOM_EXPORT
	 PyDict_SetItemString(d,"UNICODE", PyInt_FromLong(
#ifdef UNICODE
	1
#else
	0
#endif
	));
#endif
  PyWinGlobals_Ensure();
  PyDict_SetItemString(d, "error", PyWinExc_ApiError);
#endif SWIG_PYTHONCOM
